### ISSUE TITLE
Issue with PASD

### ISSUE THREAD

**Issue by zhaoyang-lv** [wutong16/HyperDreamer#1]
Hi, thanks for providing the implementation. I run into some issues when executing the code 

```
Traceback (most recent call last):
  File "main.py", line 371, in <module>
    trainer = Trainer(' '.join(sys.argv), 'df', opt, model, guidance, device=device, workspace=opt.workspace, optimizer=optimizer, ema_decay=0.95, fp16=opt.fp16, lr_scheduler=scheduler,
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/nerf/utils.py", line 226, in __init__
    self.prepare_embeddings()
  File "/data/home/zhaoyang/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/nerf/utils.py", line 437, in prepare_embeddings
    self.model_sr = infer_pasd.load_pasd_pipeline(self.sr_args, self.device, True)
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/PASD/infer_pasd.py", line 70, in load_pasd_pipeline
    text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
  File "/data/home/zhaoyang/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/data/home/zhaoyang/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
Exception ignored in: <function Trainer.__del__ at 0x7f26a2fdeb80>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/nerf/utils.py", line 452, in __del__
    if self.log_ptr:
AttributeError: 'Trainer' object has no attribute 'log_ptr'
```

It seems run into issue initializing models for PASD module. When looking at the doc, it said
```
PASD for super-resolution module
Download SD1.5 models from [huggingface](https://huggingface.co/runwayml/stable-diffusion-v1-5) and put them into PASD/checkpoints/stable-diffusion-v1-5
Download PASD pre-trained models [pasd](https://public-vigen-video.oss-cn-shanghai.aliyuncs.com/robin/models/PASD/pasd.zip) and put it into runs/.
```

Here is my folder structure
```
runs
├── checkpoint-100000
│   ├── controlnet
│   │   ├── config.json
│   │   └── diffusion_pytorch_model.safetensors
│   ├── scaler.pt
│   └── unet
│       ├── config.json
│       └── diffusion_pytorch_model.safetensors
└── pasd.zip -> /source_1a/models/DTC/pretrained_models/PASD/pasd.zip
```
```
PASD/checkpoints/stable-diffusion-v1-5
├── README.md
├── feature_extractor
│   └── preprocessor_config.json
├── model_index.json
├── safety_checker
│   ├── config.json
│   ├── model.fp16.safetensors
│   ├── model.safetensors
│   ├── pytorch_model.bin
│   └── pytorch_model.fp16.bin
├── scheduler
│   └── scheduler_config.json
├── text_encoder
│   ├── config.json
│   ├── model.fp16.safetensors
│   ├── model.safetensors
│   ├── pytorch_model.bin
│   └── pytorch_model.fp16.bin
├── tokenizer
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── unet
│   ├── config.json
│   ├── diffusion_pytorch_model.bin
│   ├── diffusion_pytorch_model.fp16.bin
│   ├── diffusion_pytorch_model.fp16.safetensors
│   ├── diffusion_pytorch_model.non_ema.bin
│   ├── diffusion_pytorch_model.non_ema.safetensors
│   └── diffusion_pytorch_model.safetensors
├── v1-5-pruned-emaonly.ckpt
├── v1-5-pruned-emaonly.safetensors
├── v1-5-pruned.ckpt
├── v1-5-pruned.safetensors
├── v1-inference.yaml
└── vae
    ├── config.json
    ├── diffusion_pytorch_model.bin
    ├── diffusion_pytorch_model.fp16.bin
    ├── diffusion_pytorch_model.fp16.safetensors
    └── diffusion_pytorch_model.safetensors
```

Any ideas what the issue is and how to fix?

**Comment by Lizb6626** [comment]
Please place the dictionary  `checkpoint-100000` inside `PASD/runs/pasd`. I apologize for the mistake in the readme.

The folder structure should be as follows:
```sh
tree -d PASD/

PASD/
├── annotator
│   ├── ckpts
│   ├── retinaface
│   │   ├── data
│   │   │   └── FDDB
│   │   ├── facemodels
│   │   ├── layers
│   │   │   ├── functions
│   │   │   └── modules
│   │   └── utils
│   │       └── nms
│   └── yolo
├── checkpoints
│   ├── personalized_models
│   │   └── unet_disney
│   └── stable-diffusion-v1-5 -> /mnt/petrelfs/lizhibing/pretrained_models/huggingface/stable-diffusion-v1-5
├── dataloader
├── datasets
├── models
│   ├── pasd
│   │   └── __pycache__
│   └── pasd_light
├── myutils
│   └── __pycache__
├── pipelines
│   └── __pycache__
├── __pycache__
└── runs
    ├── pasd
    │   └── checkpoint-100000
    │       ├── controlnet
    │       └── unet
    ├── pasd_light
    ├── pasd_light_rrdb
    └── pasd_rrdb
```

**Comment by zhaoyang-lv** [comment]
the same error still persists after move the files. Here is what my files look like now 
```
PASD/
├── __pycache__
├── annotator
│   ├── ckpts
│   ├── retinaface
│   │   ├── data
│   │   │   └── FDDB
│   │   ├── facemodels
│   │   ├── layers
│   │   │   ├── functions
│   │   │   └── modules
│   │   └── utils
│   │       └── nms
│   └── yolo
├── checkpoints
│   ├── personalized_models
│   │   └── unet_disney
│   └── stable-diffusion-v1-5 -> /source_1a/models/DTC/pretrained_models/stablediffusion/stable-diffusion-v1-5/
├── dataloader
├── datasets
├── models
│   ├── pasd
│   │   └── __pycache__
│   └── pasd_light
├── myutils
│   └── __pycache__
├── pipelines
│   └── __pycache__
└── runs
    ├── pasd
    │   └── checkpoint-100000
    │       ├── controlnet
    │       └── unet
    ├── pasd_light
    ├── pasd_light_rrdb
    └── pasd_rrdb
```
error 
```
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/PASD/infer_pasd.py", line 70, in load_pasd_pipeline
    text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
  File "/data/home/zhaoyang/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/data/home/zhaoyang/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
Exception ignored in: <function Trainer.__del__ at 0x7ff4cebb1b80>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-0b0a2c1c1faaf1aba/zhaoyang/DigitalTwinGen/baselines/HyperDreamer/nerf/utils.py", line 452, in __del__
    if self.log_ptr:
AttributeError: 'Trainer' object has no attribute 'log_ptr'
```

**Comment by Lizb6626** [comment]
It seems that your download of sd1.5 is corrupted.

Same problems can be found in [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123#issuecomment-1591991522) and [here](https://github.com/guoyww/AnimateDiff/issues/34).
Re-download should fix it.

**Comment by Lizb6626** [comment]
It appears that your download of sd1.5 is corrupted.  See https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123#issuecomment-1591991522 and https://github.com/guoyww/AnimateDiff/issues/34.

I suggest trying to re-download the file.

(Apologies for mistakenly closing the issue.)

**Comment by zhaoyang-lv** [comment]
Thanks! That takes care of it.
