### ISSUE TITLE
ModuleNotFoundError: No module named 'editing'

### ISSUE THREAD

**Issue by Arakawa-Youhei** [wutong16/HyperDreamer#7]
Hi @Lizb6626 
I run
`python editing/scripts/run_editing.py --config_path=editing/configs/sculpture.yaml
`

File "/home/arakawa/HyperDreamer/editing/scripts/run_editing.py", line 3, in <module>
    from editing.src.configs.train_config import TrainConfig
ModuleNotFoundError: No module named 'editing'

What should I do ?

**Comment by YS-IMTech** [comment]
Hi, we fix some bugs in editing module, Please update to the latest version and it will run successfully. But your error seems unrelated to this. Can I see your log?

**Comment by Arakawa-Youhei** [comment]
My log is 
`commit 2870e4aa1cc58b22da20b3d815d1edc4e9f66179 (HEAD -> master, origin/master, origin/HEAD)
Author: ys-imtech <yssss.mikey@gmail.com>
Date:   Fri Oct 4 13:48:29 2024 +0800

    fix editing module

commit b9728d19f9f09964900538d5e44922724c902cfc
Author: Lizb6626 <lizhibingcst@gmail.com>
Date:   Fri Oct 4 02:19:45 2024 +0800

    fix bug of load envmap

commit 3eb3137accfc7fcb6561f49f388b9bc9f068a2de
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Tue Apr 9 11:37:34 2024 +0800

    update

commit d9bd282b4ba86ae630ec40cd5a7d3bbace37a045
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Mon Apr 8 23:28:18 2024 +0800

    update

commit c8e597e3a54be038b9773277071616fefe8775e6
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Mon Apr 8 23:23:46 2024 +0800

    update

commit 57569b43a61756fe1982b3ac9389e55a7b897dca
Author: ys-imtech <yssss.mikey@gmail.com>
Date:   Mon Apr 8 23:18:02 2024 +0800

    update

commit bd1931635495f4e924d652fbd67958d481984383
:
`

**Comment by Arakawa-Youhei** [comment]
My log is 

commit 2870e4aa1cc58b22da20b3d815d1edc4e9f66179 (HEAD -> master, origin/master, origin/HEAD)
Author: ys-imtech <yssss.mikey@gmail.com>
Date:   Fri Oct 4 13:48:29 2024 +0800

    fix editing module

commit b9728d19f9f09964900538d5e44922724c902cfc
Author: Lizb6626 <lizhibingcst@gmail.com>
Date:   Fri Oct 4 02:19:45 2024 +0800

    fix bug of load envmap

commit 3eb3137accfc7fcb6561f49f388b9bc9f068a2de
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Tue Apr 9 11:37:34 2024 +0800

    update

commit d9bd282b4ba86ae630ec40cd5a7d3bbace37a045
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Mon Apr 8 23:28:18 2024 +0800

    update

commit c8e597e3a54be038b9773277071616fefe8775e6
Author: Shuai Yang <65273749+YS-IMTech@users.noreply.github.com>
Date:   Mon Apr 8 23:23:46 2024 +0800

    update

commit 57569b43a61756fe1982b3ac9389e55a7b897dca
Author: ys-imtech <yssss.mikey@gmail.com>
Date:   Mon Apr 8 23:18:02 2024 +0800

    update

commit bd1931635495f4e924d652fbd67958d481984383

**Comment by YS-IMTech** [comment]
This is not running log. Can I see the complete log of the above run error?

**Comment by Arakawa-Youhei** [comment]
Sorry.

arakawa@vcldeeplearningbox:~/HyperDreamer$ python editing/scripts/run_editing.py --config_path=editing/configs/sculpture.yaml
Traceback (most recent call last):
  File "/home/arakawa/HyperDreamer/editing/scripts/run_editing.py", line 3, in <module>
    from editing.src.configs.train_config import TrainConfig
ModuleNotFoundError: No module named 'editing'

**Comment by YS-IMTech** [comment]
Hi, you should run the script in the root dir(hyperdreamer). 
I suggest you check if you have editing/src/configs/train_config.py in your directory and reload your IDE and try again.

**Comment by Arakawa-Youhei** [comment]
arakawa@vcldeeplearningbox:~$ python HyperDreamer/editing/scripts/run_editing.py --config_path=HyperDreamer/editing/configs/sculpture.yaml
Traceback (most recent call last):
  File "/home/arakawa/HyperDreamer/editing/scripts/run_editing.py", line 3, in <module>
    from editing.src.configs.train_config import TrainConfig
ModuleNotFoundError: No module named 'editing'
